//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



// Type created for JSON at <<root>>
[System.Runtime.Serialization.DataContractAttribute()]
public partial class RootClass
{

    [System.Runtime.Serialization.DataMemberAttribute()]
    public Results[] results;

    [System.Runtime.Serialization.DataMemberAttribute()]
    public string status;
}

// Type created for JSON at <<root>> --> results
[System.Runtime.Serialization.DataContractAttribute(Name = "results")]
public partial class Results
{

    [System.Runtime.Serialization.DataMemberAttribute()]
    public Address_components[] address_components;

    [System.Runtime.Serialization.DataMemberAttribute()]
    public string formatted_address;

    [System.Runtime.Serialization.DataMemberAttribute()]
    public Geometry geometry;

    [System.Runtime.Serialization.DataMemberAttribute()]
    public string place_id;

    [System.Runtime.Serialization.DataMemberAttribute()]
    public string[] types;
}

// Type created for JSON at <<root>> --> address_components
[System.Runtime.Serialization.DataContractAttribute(Name = "address_components")]
public partial class Address_components
{

    [System.Runtime.Serialization.DataMemberAttribute()]
    public string long_name;

    [System.Runtime.Serialization.DataMemberAttribute()]
    public string short_name;

    [System.Runtime.Serialization.DataMemberAttribute()]
    public string[] types;
}

// Type created for JSON at <<root>>
[System.Runtime.Serialization.DataContractAttribute(Name = "geometry")]
public partial class Geometry
{

    [System.Runtime.Serialization.DataMemberAttribute()]
    public Location location;

    [System.Runtime.Serialization.DataMemberAttribute()]
    public string location_type;

    [System.Runtime.Serialization.DataMemberAttribute()]
    public Viewport viewport;

    [System.Runtime.Serialization.DataMemberAttribute()]
    public Bounds bounds;
}

// Type created for JSON at <<root>> --> geometry --> location
[System.Runtime.Serialization.DataContractAttribute(Name = "location")]
public partial class Location
{

    [System.Runtime.Serialization.DataMemberAttribute()]
    public double lat;

    [System.Runtime.Serialization.DataMemberAttribute()]
    public double lng;
}

// Type created for JSON at <<root>> --> geometry --> viewport
[System.Runtime.Serialization.DataContractAttribute(Name = "viewport")]
public partial class Viewport
{

    [System.Runtime.Serialization.DataMemberAttribute()]
    public Northeast northeast;

    [System.Runtime.Serialization.DataMemberAttribute()]
    public Southwest southwest;
}

// Type created for JSON at <<root>> --> geometry --> viewport --> northeast
[System.Runtime.Serialization.DataContractAttribute(Name = "northeast")]
public partial class Northeast
{

    [System.Runtime.Serialization.DataMemberAttribute()]
    public double lat;

    [System.Runtime.Serialization.DataMemberAttribute()]
    public double lng;
}

// Type created for JSON at <<root>> --> geometry --> viewport --> southwest
[System.Runtime.Serialization.DataContractAttribute(Name = "southwest")]
public partial class Southwest
{

    [System.Runtime.Serialization.DataMemberAttribute()]
    public double lat;

    [System.Runtime.Serialization.DataMemberAttribute()]
    public double lng;
}

// Type created for JSON at <<root>> --> geometry --> bounds
[System.Runtime.Serialization.DataContractAttribute(Name = "bounds")]
public partial class Bounds
{

    [System.Runtime.Serialization.DataMemberAttribute()]
    public Northeast1 northeast;

    [System.Runtime.Serialization.DataMemberAttribute()]
    public Southwest1 southwest;
}

// Type created for JSON at <<root>> --> geometry --> bounds --> northeast
[System.Runtime.Serialization.DataContractAttribute(Name = "northeast")]
public partial class Northeast1
{

    [System.Runtime.Serialization.DataMemberAttribute()]
    public double lat;

    [System.Runtime.Serialization.DataMemberAttribute()]
    public double lng;
}

// Type created for JSON at <<root>> --> geometry --> bounds --> southwest
[System.Runtime.Serialization.DataContractAttribute(Name = "southwest")]
public partial class Southwest1
{

    [System.Runtime.Serialization.DataMemberAttribute()]
    public double lat;

    [System.Runtime.Serialization.DataMemberAttribute()]
    public double lng;
}
